### ISSUE TITLE
Zoomed-in display on CAT-I

### ISSUE THREAD

**Issue by GerbilSoft** [GaryOderNichts/WiiUIdent#8]
On my CAT-I, the display is horribly zoomed in. I thought it might have been related to the TV resolution (which was set to 1280x720), but changing it to 1920x1080 made no difference.

Using a local RPX build with Tiramisu.

![LG_Smart_TV 2023-04-01 02-00-13](https://user-images.githubusercontent.com/6764716/229271114-ef0d0c7e-10bc-4e2c-9a97-1251ee20a028.jpg)

![LG_Smart_TV 2023-04-01 02-00-22](https://user-images.githubusercontent.com/6764716/229271118-155f567e-ba38-444d-9ea6-d35ac1c61898.jpg)

**Comment by GaryOderNichts** [comment]
Yeah, that happens if you build WiiUIdent with `wiiu-sdl` from the pacman repos.
WiiUIdent currently uses a [custom SDL 2.22 build](https://github.com/GaryOderNichts/SDL/tree/wiiu-sdl2-2.0.22) instead of the one in the pacman repos. The one in the pacman repos comes with several bugs, and always uses a 720p buffer internally.
I recommend just building with the `Dockerfile` or building and installing the custom updated SDL.

**Comment by GerbilSoft** [comment]
That'd do it. I'll build the custom one later today.

**Comment by GaryOderNichts** [comment]
The updated SDL2 build is now in the devkitPro pacman repos and WiiUIdent no longer requires a custom build (see 0143b2e867d0a4d371f79ea03a5bf2173f74658c).
